### ISSUE TITLE
Converter oversanitization of empty strings

### ISSUE THREAD

**Issue by osego** [concision/unpacker-toolchain#3]
It would appear that the lua tables jsonifier can be slightly overzealous with string sanitization so `""` becomes `"\"\""` instead.
Unfortunately, it would also appear that some strings in packages actually contain quotes which presumably makes fixing this non-trivial.

Example package with empty string encoded in base64:
`eyJwYXRoIjogIi9FRS9UeXBlcy9HcmFwaGljc1Jlcy9Gb250TWF0ZXJpYWwiLCAicGFja2FnZSI6IHsiQmxlbmQiOiAiQkxFTkRfQUxQSEEiLCAiRGVmYXVsdFBoeXNpY3NNYXRlcmlhbCI6ICIvRUUvVHlwZXMvUGh5c2ljcy9NYXRlcmlhbHMvRGVmYXVsdCIsICJTaGFkZXIwIjogIi9FRS9TaGFkZXJzL0ZvbnQuaGxzbCIsICJQUzpEZXRhaWxUaWxpbmciOiAxLCAiVFg6RGlmZnVzZU1hcCI6ICIiIiIsICJUWDpEZXRhaWxNYXAiOiAiL0VFL01hdGVyaWFscy9CYXNpYy9XaGl0ZV9kLnBuZyIsICJDYXN0U2hhZG93IjogMCwgIkRlcHRoVGVzdCI6IDAsICJBbHBoYVRlc3RWYWx1ZSI6IDEyOCwgIkNvbG9yIjogIi9FRS9NYXRlcmlhbHMvQmFzaWMvV2hpdGVfZC5wbmcifX0=`

Example package where a string contains quotes encoded in base64:
`eyJwYXRoIjogIi9FRS9UeXBlcy9CYXNlL0dyb3VwIiwgInBhY2thZ2UiOiB7IkxhYmVsIjogIiJOZXcgR3JvdXAiIn19`

**Comment by concision** [comment]
This could definitely cause issues with applications built on top of this project, if they are not expecting JSON string entries to contain quotes.

However, there is an ambiguity with blindly stripping quotes from string literals though - package paths and ENUMs do not have quotes. By stripping quotes from string literals, these JSON string entries would be indistinguishable from package paths and ENUMs. This might not be an issue, depending on what data an application must be using.

Rather than automatically strip quotes, I would rather opt for a CLI/API flag (disabled by default) that will strip quotes from string literals during the JSONification process. In this scenario, any developer building an application on top of this project can determine their use case. I will create a pull request for this change shortly.
